name: Convert Website using Pandoc

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Create timestamp
        run: date --rfc-3339=seconds > lastBuild.txt

      - name: Convert using pandoc
        uses: docker://pandoc/latex:latest-ubuntu
        with:
          entrypoint: /bin/sh
          args: >- 
            -c "
            for d in */; 
            do mkdir output/$d; done;
            find ./ -iname '*.md' -type f 
            -exec sh -c 'pandoc ${0} 
            -s
            -c pandoc.css
            -B includes/header.html
            -A includes/footer.html
            -o ${0%.md}.html' {} \;"
      
      - name: Cleanup
        run: rm README.html
      
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
