name: Convert Website using Pandoc

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Create timestamp
        run: date --rfc-3339=seconds > lastBuild.txt
        
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          push: true
          default_author: github_actions
