name: Convert Website using Pandoc

on: push

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Create timestamp
        run: date --rfc-3339=seconds > lastBuild.txt
        
      - name: Commit and Push Branch
        uses: dsayling/commit-branch-check-action@v0.1.5
        with:
          github-token: ${{ github.token }}
          dest-branch: main
          commit-message: "Automated deployment"
